const validUrl = require("valid-url");
const staffManager = require('../../manager/staff');

async function postNewStaff(req, res) {
    try {
        const staff = new staffManager;
        /// uuid is generated by the front or back or bbdd
        const { id, rol, name } = req.body;

        const newStaff = await staff.postNewStaff(id, rol, name);
        if (newStaff) {
            res.json();
        } else {
            res.status(404).json("Not found");
        }
    } catch (err) {
        res.status(500).json("Server Error");
    }
}

module.exports = postNewStaff;
