const validUrl = require("valid-url");
const staffManager = require('../../manager/menu');
async function postNewStaff(req, res) {
    try {
        const staff = new staffManager;
        /// uuid is generated by the front or back or bbdd
        const { loginEmail, passWord } = req.body;
        // if it is not a valid url we cancel
        if (!validUrl.isUri(loginEmail)) {
            res.status(400).json("Invalid Url"); 
        }
        /// We validate that it is encrypted???
        const newStaff = await staff.login(loginEmail, passWord);
        if (newStaff) {
            res.json();
        } else {
            res.status(404).json("Not found");
        }
    } catch (err) {
        res.status(500).json("Server Error");
    }
}

module.exports = postNewStaff;
